apiVersion: v1
kind: ConfigMap
metadata:
  name: banking-config
  namespace: {{ .Release.Namespace }}
data:
  NODE_ENV: {{ .Values.configmap.NODE_ENV | quote }}
  PORT:     {{ .Values.configmap.PORT | quote }}
  DB_HOST:  {{ .Values.configmap.DB_HOST | quote }}
  DB_PORT:  {{ .Values.configmap.DB_PORT | quote }}
  DB_NAME:  {{ .Values.configmap.DB_NAME | quote }}
