apiVersion: v1
kind: Secret
metadata:
  name: banking-secrets
  namespace: {{ .Release.Namespace }}
type: Opaque
data:
  DB_USER:     {{ .Values.secret.DB_USER }}
  DB_PASSWORD: {{ .Values.secret.DB_PASSWORD }}
