apiVersion: apps/v1
kind: Deployment
metadata:
  name: banking-backend
  namespace: banking
  labels:
    app: banking-backend
    tier: backend
spec:
  replicas: 1
  selector:
    matchLabels:
      app: banking-backend
  template:
    metadata:
      labels:
        app: banking-backend
        tier: backend
    spec:
      terminationGracePeriodSeconds: 30
      securityContext:
        runAsUser: 1000
        fsGroup: 1000
      initContainers:
        - name: wait-for-postgres
          image: busybox:1.35
          command: ['sh', '-c', 'until nc -z postgres-service 5432; do echo "waiting..."; sleep 3; done']
      containers:
        - name: backend
          image: shivaram1918/banking-backend:latest
          imagePullPolicy: Always
          ports:
            - containerPort: 5000
              name: http
          envFrom:
            - configMapRef:
                name: banking-config
            - secretRef:
                name: banking-secrets
          resources:
            requests:
              cpu: "50m"
              memory: "64Mi"
            limits:
              cpu: "200m"
              memory: "128Mi"
          startupProbe:
            httpGet:
              path: /health
              port: 5000
            failureThreshold: 30
            periodSeconds: 5
          readinessProbe:
            httpGet:
              path: /health
              port: 5000
            initialDelaySeconds: 10
            periodSeconds: 5
            failureThreshold: 3
          livenessProbe:
            httpGet:
              path: /health
              port: 5000
            initialDelaySeconds: 20
            periodSeconds: 10
            failureThreshold: 3
---
apiVersion: v1
kind: Service
metadata:
  name: banking-backend
  namespace: banking
spec:
  selector:
    app: banking-backend
  ports:
    - name: http
      port: 5000
      targetPort: 5000
  type: ClusterIP
