---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: banking-backend
  namespace: banking
  labels:
    app: banking-backend
    tier: backend
spec:
  replicas: 2

  selector:
    matchLabels:
      app: banking-backend

  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 0

  template:
    metadata:
      labels:
        app: banking-backend
        tier: backend

    spec:
      terminationGracePeriodSeconds: 30

      securityContext:
        runAsNonRoot: true
        fsGroup: 1000

      containers:
        - name: backend
          image: IMAGE_BACKEND   # ✅ replaced dynamically via CI/CD
          imagePullPolicy: Always

          ports:
            - containerPort: 5000

          envFrom:
            - configMapRef:
                name: banking-config
            - secretRef:
                name: banking-secrets

          resources:
            requests:
              cpu: "100m"
              memory: "128Mi"
            limits:
              cpu: "300m"
              memory: "256Mi"

          readinessProbe:
            httpGet:
              path: /health
              port: 5000
            initialDelaySeconds: 10
            periodSeconds: 5

          livenessProbe:
            httpGet:
              path: /health
              port: 5000
            initialDelaySeconds: 20
            periodSeconds: 10

          startupProbe:
            httpGet:
              path: /health
              port: 5000
            failureThreshold: 30
            periodSeconds: 5

          lifecycle:
            preStop:
              exec:
                command: ["/bin/sh", "-c", "sleep 5"]

---
apiVersion: v1
kind: Service
metadata:
  name: banking-backend-service
  namespace: banking
spec:
  selector:
    app: banking-backend
  ports:
    - port: 5000
      targetPort: 5000
  type: ClusterIP

---
apiVersion: policy/v1
kind: PodDisruptionBudget
metadata:
  name: backend-pdb
  namespace: banking
spec:
  minAvailable: 1
  selector:
    matchLabels:
      app: banking-backend

---
apiVersion: autoscaling/v2
kind: HorizontalPodAutoscaler
metadata:
  name: banking-backend-hpa
  namespace: banking
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: banking-backend

  minReplicas: 2
  maxReplicas: 6

  metrics:
    - type: Resource
      resource:
        name: cpu
        target:
          type: Utilization
          averageUtilization: 70

    - type: Resource
      resource:
        name: memory
        target:
          type: Utilization
          averageUtilization: 80
